services:
  - type: static_site
    name: issue-reporting-system
    buildCommand: cd Frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: Frontend/dist
    env: node
    routes:
      - path: /*
        destination: /index.html
